name: Build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install `libsdl2`
        run: sudo apt-get install libsdl2-dev
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Build project with Cargo
        run: cargo build --verbose
      - name: Run tests with Cargo
        run: cargo test --verbose
      - name: Check formatting with Rustfmt
        uses: actions-rust-lang/rustfmt@v1
